### ISSUE TITLE
conda python version 3.8.16 libffi error

### ISSUE THREAD

**Issue by DuaneNielsen** [tonyzhaozh/aloha#3]
Hey Tony,

Latest 3.8.16 version of python is broken on Ubuntu 20.04

will give the below error.. (when executing recording.py)

```
cv_bridge.boost.cv_bridge_boost import getCvType
ImportError: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0
```

This is due to an incompatibility between the libffi shipped with 20.04, and the version python 3.8.16 expects..  ( think it's 3.3 in 20.04 but python is expecting 3.4... something like that)

```
conda install python=3.8.10
```

in the aloha environment fixes the problem.

Recommend specifying 3.8.10 in the README.md instead of 3.8 as current

**Comment by tonyzhaozh** [comment]
Hi Duane,

Sorry for the late reply as I have been quite busy lately. I actually encountered the same error when installing Aloha in a new computer, and have been quite perplexed by it. Looks like this is the root cause and thanks for catching it!

I just updated the requirement [here](https://github.com/tonyzhaozh/aloha/commit/f3306d42e800b6d486c309bebf316fe06103e86b).

Aloha,
Tony
