### ISSUE TITLE
How can I get the Collected real-world data in the paper?

### ISSUE THREAD

**Issue by LYX0501** [tonyzhaozh/aloha#5]
Could you please tell me how can I get the collected real-world data in you paper?

**Comment by tonyzhaozh** [comment]
Hi. We are not planning to release the data in the short term, but have the plan to do so in the longer term.

The reason is a bit complicated. We used a legacy low-level controller for paper experiments, and later realized a way to improve it. The released version of Aloha contains the improved controller, which are not compatible with the old data. I.e. if you replay the old data with open-source version of the code, it will not perfectly perform the task.

Thus we will technically need to re-collect the data if we want to release it. But with that said we have also switched to the new controller and have new data coming in that is compatible. We will do a release when it hits a certain critical mass, and potentially organize data sharing between all users of Aloha.

Thanks,
Tony

**Comment by LYX0501** [comment]
Thank you for your response! Looking forward to the data release.
